#!/usr/bin/env ruby
#^syntax detection

ckbks 'http://www.cookbooks.io'

cookbook 'ss-chef-mysql'

cookbook 'ss-chef-rvm', '>= 0.8.0'
cookbook 'oc-java'
cookbook 'oc-runit'
cookbook 'oc-activemq'
#cookbook 'ss-chef-gitorious'
