- ant
- apt
- bazaar
- bison
- build-essential
- cassandra
- chromium
- clang
- cmake
- composer
- couchdb
- doxygen
- elasticsearch
- emacs
- erlang
- firefox
- git
- golang
- gradle
- gvm
- haskell
- hbase
- htop
- imagemagick
- iptables
- java
- kerl
- kestrel
- leiningen
- libffi
- libgdbm
- libncurses
- libossp-uuid
- libqt4
- libreadline
- libssl
- libxml
- libyaml
- lighttpd
- maven3
- memcached
- mercurial
- mingw32
- mongodb
- mysql
- neo4j-server
- networking_basic
- nodejs
- openssh
- openssl
- perlbrew
- phantomjs
- php
- phpbuild
- phpenv
- postgresql
- pypy
- python
- rabbitmq
- ragel
- ramfs
- rebar
- redis
- riak
- rvm
- sbt
- scons
- sphinx
- sqlite
- subversion
- sweeper
- sysctl
- timezone
- travis_build_environment
- unarchivers
- util-linux
- vim
- xserver
- zeromq
- zookeeper